import type { User, Dataset, Alert } from '@/types'

/**
 * Seed data for development and testing
 */

export const seedUsers: User[] = [
  {
    id: '1',
    email: 'meera@example.com',
    name: 'Meera Patel',
    role: 'it_admin',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    email: 'ravi@example.com',
    name: 'Ravi Kumar',
    role: 'data_steward',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    email: 'asha@example.com',
    name: 'Asha Sharma',
    role: 'business_analyst',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    email: 'vikram@example.com',
    name: 'Vikram Singh',
    role: 'exec',
    createdAt: new Date().toISOString(),
  },
]

export const seedDatasets: Dataset[] = [
  {
    id: 'ds-1',
    name: 'Customer Master Database',
    domain: 'Sales',
    description: 'Primary customer data repository containing contact information, demographics, and purchase history',
    schema: {},
    profile: {
      totalRows: 125000,
      totalColumns: 22,
      completeness: 0.92,
      validity: 0.88,
      uniqueness: 0.94,
      missingValues: 10000,
      nullRate: { email: 0.08, phone: 0.05, address: 0.12 },
      dupRate: 0.06,
      outliers: ['age', 'lifetime_value'],
      patterns: { email: 'email', phone: 'phone', zip_code: 'numeric' },
    },
    badge: 'Silver',
    qualityScore: 0.91,
    owner: '2',
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-2',
    name: 'Marketing Leads Q4 2024',
    domain: 'Marketing',
    description: 'Q4 marketing campaign leads with lead scores, source tracking, and conversion data',
    schema: {},
    profile: {
      totalRows: 45000,
      totalColumns: 18,
      completeness: 0.78,
      validity: 0.72,
      uniqueness: 0.85,
      missingValues: 9900,
      nullRate: { phone: 0.22, company_size: 0.15, industry: 0.08 },
      dupRate: 0.15,
      outliers: ['lead_score'],
      patterns: { email: 'email', company: 'text', source: 'categorical' },
    },
    badge: 'Bronze',
    qualityScore: 0.78,
    owner: '3',
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-3',
    name: 'Financial Transactions',
    domain: 'Finance',
    description: 'Complete transaction ledger for financial reporting, audit compliance, and revenue recognition',
    schema: {},
    profile: {
      totalRows: 2500000,
      totalColumns: 16,
      completeness: 0.99,
      validity: 0.97,
      uniqueness: 0.998,
      missingValues: 25000,
      nullRate: { merchant_category: 0.01, description: 0.02 },
      dupRate: 0.002,
      outliers: [],
      patterns: { transaction_id: 'uuid', amount: 'decimal', date: 'timestamp' },
    },
    badge: 'Gold',
    qualityScore: 0.98,
    owner: '2',
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-4',
    name: 'Product Catalog & Inventory',
    domain: 'Ops',
    description: 'Master product catalog with SKU management, pricing, inventory levels, and supplier information',
    schema: {},
    profile: {
      totalRows: 45000,
      totalColumns: 28,
      completeness: 0.96,
      validity: 0.94,
      uniqueness: 0.97,
      missingValues: 1800,
      nullRate: { supplier_id: 0.04, warehouse_location: 0.03, weight: 0.05 },
      dupRate: 0.03,
      outliers: ['price', 'stock_level'],
      patterns: { sku: 'alphanumeric', barcode: 'numeric', price: 'decimal' },
    },
    badge: 'Gold',
    qualityScore: 0.96,
    owner: '2',
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-5',
    name: 'Order Management System',
    domain: 'Sales',
    description: 'E-commerce order tracking including order details, shipping, payments, and fulfillment status',
    schema: {},
    profile: {
      totalRows: 380000,
      totalColumns: 24,
      completeness: 0.89,
      validity: 0.91,
      uniqueness: 0.95,
      missingValues: 41800,
      nullRate: { shipping_address: 0.05, tracking_number: 0.08, customer_notes: 0.35 },
      dupRate: 0.05,
      outliers: ['order_value', 'shipping_cost'],
      patterns: { order_id: 'alphanumeric', order_date: 'timestamp', status: 'categorical' },
    },
    badge: 'Silver',
    qualityScore: 0.92,
    owner: '2',
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-6',
    name: 'Employee Directory',
    domain: 'HR',
    description: 'Employee master data with personal info, job details, compensation, and organizational hierarchy',
    schema: {},
    profile: {
      totalRows: 8500,
      totalColumns: 32,
      completeness: 0.94,
      validity: 0.96,
      uniqueness: 0.99,
      missingValues: 510,
      nullRate: { emergency_contact: 0.06, middle_name: 0.15, bonus: 0.12 },
      dupRate: 0.01,
      outliers: ['salary'],
      patterns: { employee_id: 'numeric', ssn: 'ssn', email: 'email', hire_date: 'date' },
    },
    badge: 'Gold',
    qualityScore: 0.96,
    owner: '1',
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-7',
    name: 'Website Analytics Events',
    domain: 'Marketing',
    description: 'User behavior tracking from web analytics including page views, clicks, sessions, and conversions',
    schema: {},
    profile: {
      totalRows: 15000000,
      totalColumns: 14,
      completeness: 0.86,
      validity: 0.84,
      uniqueness: 0.92,
      missingValues: 2100000,
      nullRate: { user_id: 0.14, referrer: 0.18, utm_campaign: 0.22 },
      dupRate: 0.08,
      outliers: ['session_duration'],
      patterns: { event_id: 'uuid', timestamp: 'timestamp', user_agent: 'text' },
    },
    badge: 'Silver',
    qualityScore: 0.87,
    owner: '3',
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-8',
    name: 'Supplier Master Data',
    domain: 'Ops',
    description: 'Supplier and vendor information including contracts, performance metrics, and contact details',
    schema: {},
    profile: {
      totalRows: 2800,
      totalColumns: 26,
      completeness: 0.91,
      validity: 0.88,
      uniqueness: 0.96,
      missingValues: 252,
      nullRate: { tax_id: 0.09, payment_terms: 0.05, rating: 0.12 },
      dupRate: 0.04,
      outliers: ['annual_spend'],
      patterns: { supplier_id: 'numeric', email: 'email', country: 'iso_code' },
    },
    badge: 'Silver',
    qualityScore: 0.92,
    owner: '2',
    createdAt: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-9',
    name: 'Customer Support Tickets',
    domain: 'Support',
    description: 'Help desk ticketing system with customer inquiries, issue tracking, and resolution history',
    schema: {},
    profile: {
      totalRows: 95000,
      totalColumns: 20,
      completeness: 0.83,
      validity: 0.79,
      uniqueness: 0.98,
      missingValues: 16150,
      nullRate: { customer_id: 0.17, resolution_notes: 0.21, satisfaction_score: 0.42 },
      dupRate: 0.02,
      outliers: ['resolution_time'],
      patterns: { ticket_id: 'numeric', created_at: 'timestamp', priority: 'categorical' },
    },
    badge: 'Bronze',
    qualityScore: 0.80,
    owner: '3',
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-10',
    name: 'Sales Pipeline & Opportunities',
    domain: 'Sales',
    description: 'CRM opportunity tracking with deal stages, revenue forecasts, and sales rep assignments',
    schema: {},
    profile: {
      totalRows: 12000,
      totalColumns: 19,
      completeness: 0.88,
      validity: 0.85,
      uniqueness: 0.97,
      missingValues: 1440,
      nullRate: { close_date: 0.12, next_step: 0.18, competitor: 0.25 },
      dupRate: 0.03,
      outliers: ['deal_value'],
      patterns: { opportunity_id: 'uuid', stage: 'categorical', probability: 'percentage' },
    },
    badge: 'Silver',
    qualityScore: 0.90,
    owner: '2',
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-11',
    name: 'Payment Processing Records',
    domain: 'Finance',
    description: 'Payment gateway transactions with authorization, settlement, and chargeback tracking',
    schema: {},
    profile: {
      totalRows: 1800000,
      totalColumns: 18,
      completeness: 0.97,
      validity: 0.95,
      uniqueness: 0.99,
      missingValues: 54000,
      nullRate: { card_type: 0.03, billing_zip: 0.04, authorization_code: 0.02 },
      dupRate: 0.01,
      outliers: [],
      patterns: { payment_id: 'uuid', amount: 'decimal', timestamp: 'timestamp' },
    },
    badge: 'Gold',
    qualityScore: 0.97,
    owner: '2',
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'ds-12',
    name: 'Email Campaign Performance',
    domain: 'Marketing',
    description: 'Email marketing metrics including opens, clicks, bounces, and conversion tracking',
    schema: {},
    profile: {
      totalRows: 580000,
      totalColumns: 16,
      completeness: 0.81,
      validity: 0.76,
      uniqueness: 0.88,
      missingValues: 110200,
      nullRate: { click_timestamp: 0.19, conversion_value: 0.24, device_type: 0.15 },
      dupRate: 0.12,
      outliers: ['open_count'],
      patterns: { campaign_id: 'alphanumeric', sent_at: 'timestamp', email: 'email' },
    },
    badge: 'Bronze',
    qualityScore: 0.82,
    owner: '3',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    lastModified: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
]

export const seedAlerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'pii_violation',
    severity: 'high',
    datasetId: 'ds-2',
    message: 'PII data detected in Marketing Leads Q4 2024 - SSN and credit card numbers found in notes field',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-2',
    type: 'uniqueness_drop',
    severity: 'high',
    datasetId: 'ds-1',
    message: 'Duplicate rate increased from 4% to 6% in Customer Master Database - 2,500 duplicate records detected',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-3',
    type: 'freshness_drop',
    severity: 'medium',
    datasetId: 'ds-2',
    message: 'Marketing Leads Q4 2024 has not been updated in 5 days - data may be stale',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    ackBy: '2',
  },
  {
    id: 'alert-4',
    type: 'completeness_drop',
    severity: 'high',
    datasetId: 'ds-9',
    message: 'Customer Support Tickets completeness dropped to 83% - 16,150 missing values across critical fields',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-5',
    type: 'validity_drop',
    severity: 'medium',
    datasetId: 'ds-12',
    message: 'Email Campaign Performance has 24% invalid email addresses - bounce rate threshold exceeded',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    ackBy: '3',
  },
  {
    id: 'alert-6',
    type: 'schema_change',
    severity: 'medium',
    datasetId: 'ds-4',
    message: 'Product Catalog & Inventory schema changed - 3 new columns added, 1 column removed',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    ackBy: '2',
  },
  {
    id: 'alert-7',
    type: 'anomaly',
    severity: 'low',
    datasetId: 'ds-7',
    message: 'Website Analytics Events showing unusual spike in session_duration outliers (+340% above baseline)',
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-8',
    type: 'pii_violation',
    severity: 'high',
    datasetId: 'ds-6',
    message: 'Employee Directory contains unmasked SSN data in non-production environment',
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
]

/**
 * Initialize stores with seed data for development and demo
 */
export function initializeSeedData() {
  // Load seed data in development AND production (for demo purposes)
  // Import stores dynamically to avoid circular dependencies
  import('@/stores').then(({ useAuthStore, useDatasetsStore, useAlertsStore }) => {
    // Seed auth with Ravi (Data Steward) as default user
    const authStore = useAuthStore.getState()
    if (!authStore.isAuthenticated) {
      authStore.login(seedUsers[1], [
        'rules.create',
        'rules.update',
        'dq.run',
        'sla.manage',
        'alerts.manage',
        'exports.read',
        'datasets.read',
      ])
    }

    // Seed datasets
    const datasetsStore = useDatasetsStore.getState()
    if (datasetsStore.datasets.length === 0) {
      datasetsStore.setDatasets(seedDatasets)
    }

    // Seed alerts
    const alertsStore = useAlertsStore.getState()
    if (alertsStore.alerts.length === 0) {
      alertsStore.setAlerts(seedAlerts)
    }
  })
}
